announcement_banner:
  desktop_message: "<span>Join Datadog at DASH—coming to NYC June 9-10. Register now for Super Early Bird savings of $700 until March 31</span>"
  mobile_message: "<span>Join us at DASH—June 9-10. Save $700 until March 31</span>"
  background_color: "#000000"
  custom_classes: 'dash-announcement-banner'
  external_link: https://dash.datadoghq.com/?utm_source=events&utm_medium=internal&utm_campaign=summit-202606dash&utm_term=HPbanner
disclaimer: Cette page n'est pas encore disponible en français, sa traduction est
  en cours. <br> Si vous avez des questions ou des retours sur notre projet  de traduction
  actuel, <a href="https://docs.datadoghq.com/fr/help/">n'hésitez pas à nous contacter</a>.
meta_description: Datadog, le principal prestataire de services de surveillance à
  l'échelle du cloud.
meta_title: Débuter avec Datadog
site_name: Surveillance d'applications et d'infrastructures avec Datadog
site_support_banner: Ce produit n'est pas pris en charge par le <a href="/getting_started/site">site
  Datadog </a> que vous avez sélectionné.
translate_status_banner: Cette traduction n'est pas à jour. Pour consulter la dernière
  version en anglais, cliquez ici
