announcement_banner:
  desktop_message: "<span>Join Datadog at DASH—coming to NYC June 9-10. Register now for Super Early Bird savings of $700 until March 31</span>"
  mobile_message: "<span>Join us at DASH—June 9-10. Save $700 until March 31</span>"
  background_color: "#000000"
  custom_classes: 'dash-announcement-banner'
  external_link: https://dash.datadoghq.com/?utm_source=events&utm_medium=internal&utm_campaign=summit-202606dash&utm_term=HPbanner
disclaimer: Esta página aún no está disponible en español. Estamos trabajando en su
  traducción. <br> Si tienes alguna pregunta o comentario sobre nuestro actual proyecto
  de traducción, <a href="https://docs.datadoghq.com/es/help/">no dudes en ponerte
  en contacto con nosotros</a>.
meta_description: Datadog, el servicio líder de monitorización a escala en nube.
meta_title: Empezando con Datadog
site_name: Monitorización de la infraestructura y las aplicaciones de Datadog
site_support_banner: Este producto no es compatible con el <a href="/getting_started/site">sitio
  Datadog</a> seleccionado.
translate_status_banner: Esta traducción no está actualizada. Para consultar la última
  versión en inglés, haz clic aquí
